[[section-building-block-view]]


== Building Block View

The truth of how a system is implemented, is in the code. This alone, however, is rarely enough to understand a system as a whole. Therefore it is necessary to offer the possibility to dive deeper and deeper into the system, starting from a relatively high level of flight.

These possiblity is offered by the "Building Block Views". The following table gives an overview of how the building block views, C4 diagrams and DDD are connectable.

.Building Block Views Mapping
[%header,cols=3*] 
|===
|arc42 Building Block View
|C4 Model
|DDD

|Level 1
|Container diagram
|Technical view of the Context Map +
(Bounded Context as container)

|Level 2
|Component diagram
|View on the Aggregate(s) +
of a Bounded Context 

|Level 3
|Class diagram
|Always generate class diagrams from code, +
Otherwise they outdate too quickly. +
The following example is generated during each build. +
When using BCE, just the control and entity packages are necessary. +
The contents of the boundary package are implementation details and not building blocks, +
because an system should be build upon domain logic and not technical details. +
The necessary informations about this layer are visible in the container diagram or <<Deployment View>>.
|===

For further information see https://docs.arc42.org/section-5/[Building Block View] in the arc42 documentation.

=== Class diagram

NOTE: This diagram is optional and should just be used when required to understand parts of a system.

[plantuml, author_aggregate]
----
include::../plantuml/author_aggregate.puml[]
----
